<a href="https://colab.research.google.com/github/SIVASHANKARI04/Students-Success-Matrics/blob/main/Students_Success_Metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/students performance analysis 1.csv")

In [4]:
df

,age,Hours_Studied,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Family_Income,School_Type,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,Low,No,7,73,Low,Yes,Low,Public,3,No,High School,Near,Male,67
1,19,Low,No,8,59,Low,Yes,Medium,Public,4,No,College,Moderate,Female,61
2,24,Medium,Yes,7,91,Medium,Yes,Medium,Public,4,No,Postgraduate,Near,Male,74
3,29,Low,Yes,8,98,Medium,Yes,Medium,Public,4,No,High School,Moderate,Male,71
4,19,Medium,Yes,6,65,Medium,Yes,Medium,Public,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,High,No,7,76,Medium,Yes,High,Public,2,No,High School,Near,Female,68
6603,23,High,No,8,81,Medium,Yes,Low,Public,2,No,High School,Near,Female,69
6604,20,Medium,Yes,6,65,Low,Yes,Low,Public,2,No,Postgraduate,Near,Female,68
6605,10,High,Yes,6,91,High,Yes,Low,Private,3,No,High School,Far,Female,68
6606,15,Medium,Yes,9,94,Medium,Yes,Medium,Public,4,No,Postgraduate,Near,Male,64

#1.Select all records where the student's Exam Score is above 85.

In [5]:
df[df["Exam_Score"]>85]

,age,Hours_Studied,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Family_Income,School_Type,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
94,18,High,Yes,4,73,Medium,Yes,High,Private,2,No,College,Near,Female,100
217,19,Medium,No,7,54,High,Yes,Medium,Public,2,Yes,High School,Moderate,Male,89
404,17,Low,Yes,5,53,Medium,Yes,High,Public,3,No,College,Near,Male,86
529,15,Medium,No,7,97,Medium,Yes,Low,Private,2,No,High School,Near,Female,97
770,24,Low,No,6,93,Medium,Yes,Low,Public,2,No,High School,Moderate,Female,94
836,29,Medium,No,8,96,Low,Yes,Low,Public,2,No,Postgraduate,Moderate,Male,94
919,21,High,No,6,94,Medium,Yes,Low,Public,1,No,High School,Near,Male,97
1107,14,Low,No,6,75,Medium,Yes,Medium,Public,4,Yes,High School,Near,Female,89
1109,31,Medium,No,7,52,Medium,No,High,Public,5,No,College,Far,Male,92
1525,27,Low,Yes,6,93,Low,No,High,Public,3,No,High School,Moderate,Female,101
1607,30,Medium,Yes,9,93,Medium,Yes,Low,Private,3,No,High School,Near,Male,88
1844,21,High,Yes,9,58,Medium,Yes,High,Public,5,No,High School,Moderate,Female,89
2292,21,High,No,9,66,Medium,Yes,Medium,Public,4,No,College,Moderate,Male,91
2421,27,Low,No,9,52,Low,No,Low,Public,2,Yes,College,Near,Male,86
2425,23,High,Yes,4,89,Low,Yes,Medium,Public,3,No,High School,Far,Male,99
2513,18,High,No,8,60,Medium,Yes,Low,Private,1,No,College,Near,Male,88
2595,7,Medium,Yes,8,54,High,Yes,Medium,Public,2,No,High School,Far,Male,87
2687,11,Low,Yes,8,55,Medium,Yes,Low,Public,3,No,College,Near,Female,87
2904,11,High,Yes,7,76,High,Yes,High,Private,3,Yes,High School,Moderate,Male,88
3124,19,Medium,Yes,5,90,Low,Yes,Low,Public,2,No,College,Far,Female,94
3141,7,High,Yes,10,90,Medium,Yes,Low,Private,2,Yes,High School,Moderate,Male,86
3364,16,Medium,Yes,6,63,High,Yes,Low,Public,1,No,High School,Near,Female,86
3457,18,Medium,No,7,76,Low,Yes,Medium,Private,4,No,High School,Near,Female,96
3579,14,High,Yes,8,86,Medium,Yes,Medium,Private,2,No,High School,Near,Female,99
4192,28,Low,Yes,9,91,Medium,Yes,Medium,Public,2,No,College,Moderate,Female,98
4297,21,Medium,Yes,6,88,Medium,Yes,Low,Private,5,No,Postgraduate,Near,Female,95
4405,25,Medium,Yes,7,90,High,Yes,High,Public,4,No,Postgraduate,Near,Male,94
4531,26,High,No,7,95,Low,No,Medium,Public,3,No,Postgraduate,Near,Female,93
4583,25,Medium,Yes,7,56,Medium,Yes,High,Public,4,No,High School,Near,Female,93
4779,1,Medium,Yes,4,72,High,Yes,Medium,Private,2,No,College,Near,Male,92
5966,25,Medium,Yes,7,77,Medium,Yes,High,Public,3,No,High School,Near,Male,97
6347,28,High,Yes,4,98,High,Yes,High,Public,3,No,High School,Near,Male,98
6393,16,Low,Yes,8,92,Low,Yes,High,Public,4,No,Postgraduate,Near,Female,98
6522,18,High,Yes,6,54,Low,Yes,Medium,Public,3,No,High School,Near,Female,95

#2.Sort the DataFrame based on total marks in descending order.

In [ ]:
df.sort_values(by=["Exam_Score"],ascending=False)

,age,Hours_Studied,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Family_Income,School_Type,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1525,27,Low,Yes,6,93,Low,No,High,Public,3,No,High School,Moderate,Female,101
94,18,High,Yes,4,73,Medium,Yes,High,Private,2,No,College,Near,Female,100
2425,23,High,Yes,4,89,Low,Yes,Medium,Public,3,No,High School,Far,Male,99
3579,14,High,Yes,8,86,Medium,Yes,Medium,Private,2,No,High School,Near,Female,99
6393,16,Low,Yes,8,92,Low,Yes,High,Public,4,No,Postgraduate,Near,Female,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5907,3,Medium,Yes,6,78,Low,Yes,Low,Public,1,No,Postgraduate,Near,Female,57
5719,9,Medium,Yes,10,68,Low,Yes,Medium,Private,3,No,High School,Near,Male,57
2880,7,High,Yes,8,68,High,Yes,Low,Public,2,Yes,College,Moderate,Male,57
5507,5,Low,No,7,71,Medium,Yes,Low,Private,2,No,College,Far,Male,56
1101,3,Medium,No,6,67,Medium,Yes,Low,Public,3,No,High School,Near,Male,55

#3.Rank the students based on their total marks and add the rank as a new column.

In [7]:

df['Rank'] = df['Exam_Score'].rank(method='min', ascending=False).astype(int)
df_sorted = df.sort_values(by='Rank')
df_sorted

,age,Hours_Studied,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Family_Income,School_Type,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Rank
1525,27,Low,Yes,6,93,Low,No,High,Public,3,No,High School,Moderate,Female,101,1
94,18,High,Yes,4,73,Medium,Yes,High,Private,2,No,College,Near,Female,100,2
3579,14,High,Yes,8,86,Medium,Yes,Medium,Private,2,No,High School,Near,Female,99,3
2425,23,High,Yes,4,89,Low,Yes,Medium,Public,3,No,High School,Far,Male,99,3
6347,28,High,Yes,4,98,High,Yes,High,Public,3,No,High School,Near,Male,98,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5907,3,Medium,Yes,6,78,Low,Yes,Low,Public,1,No,Postgraduate,Near,Female,57,6602
2880,7,High,Yes,8,68,High,Yes,Low,Public,2,Yes,College,Moderate,Male,57,6602
3543,14,Low,Yes,7,66,Low,Yes,Low,Public,4,No,High School,Far,Female,57,6602
5507,5,Low,No,7,71,Medium,Yes,Low,Private,2,No,College,Far,Male,56,6606
1101,3,Medium,No,6,67,Medium,Yes,Low,Public,3,No,High School,Near,Male,55,6607

#4.The count of students who failed (score < 40) in exam scores

In [10]:
df[df["Exam_Score"]<40].value_counts("Exam_Score")

Series([], Name: count, dtype: int64)

#5.Display the exam score and count of female students study in public school without internet?

In [13]:
df[(df["Gender"]=="Female") & (df["School_Type"]=="Public") & (df["Internet_Access"]=="No")]["Exam_Score"].value_counts()

Exam_Score
64     21
69     16
68     16
65     15
66     15
63     13
70     11
62     10
67      9
71      6
72      3
60      3
61      2
74      2
101     1
58      1
75      1
76      1
93      1
59      1
Name: count, dtype: int64